parameters:
  key_name: < your key name >
  public_net_id: < ID of the public net for your region >
  private_net_dns_servers: < comma-separated list of DNS server IPs >
  secgroup_webserver: < the name of the security group for this instance >
  site_name: <your site name>
  environment: <environment, e.g. test, prod ..>
  app_type: < moodle or totara >
  site_url: < your site URL >
  git_repo: < your git repo >
  git_branch: < the git branch in git_repo you want to run >
  db_root_password: < your DB root password >
