parameters:
  key_name: < your key name >
  image: ubuntu-14.04-x86_64
  servers_flavor: c1.c1r1
  public_net_id: < ID of the public net for your region >
  private_net_dns_servers: < comma-separated list of DNS server IPs >
  private_net_name: < your private net name >
  router_name: <your router name >
  ssh_ip_cidr: < originating network for SSH connections >
  site_name: catcloud
  environment: test
  app_type: < moodle or totara >
  site_url: < your site URL >
  git_repo: < your git repo >
  git_branch: < the git branch in git_repo you want to run >
  db_root_password: < your DB root password >

