#
# Infrastructure template for Moodle/Totara on a single instance plus all network infrastructure.
#

heat_template_version: 2013-05-23

description: >
  Infrastructure template for Moodle/Totara on a single instance plus all network infrastructure.
parameter_groups:
- label: Infrastructure
  description: Infrastructure configuration
  parameters:
  - key_name
  - servers_flavor
  - image
  - public_net
  - public_net_id
  - private_net_cidr
  - secgroup_server
  - private_net_gateway
  - private_net_pool_start
  - private_net_pool_end
  - private_net_dns_servers
  
- label: MoodleTotara
  description: Moodle/Totara instance configuration
  parameters:
  - site_name
  - environment
  - app_type
  - site_url
  - git_repo
  - git_branch
- label: Database
  description: Database configuration
  parameters:
  - db_root_password

parameters:

# Infrastructure

  key_name:
    type: string
    description: Name of an existing key pair to use for the server
    constraints:
      - custom_constraint: nova.keypair

  servers_flavor:
    type: string
    description: Flavour for the database servers
    default: c1.c1r1
    constraints:
      - custom_constraint: nova.flavor

  image:
    type: string
    description: Image ID or image name to use for the server
    default: ubuntu-14.04-x86_64
    constraints:
      - custom_constraint: glance.image

  public_net:
    type: string
    description: >
      ID or name of public network for which floating IP addresses will be allocated
    default: public-net

  public_net_id:
    type: string
    description: >
      ID of public network for which floating IP addresses will be allocated

  private_net_cidr:
    type: string
    description: Private network address (CIDR notation)
    default: 192.168.0.0/24
    
 secgroup_server:
    type: string
    description: Security group name
    default: mdl_1server
    
  private_net_gateway:
    type: string
    description: Private network gateway address
    default: 192.168.0.1

  private_net_pool_start:
    type: string
    description: Start of private network IP address allocation pool
    default: 192.168.0.10

  private_net_pool_end:
    type: string
    description: End of private network IP address allocation pool
    default: 192.168.0.250

  private_net_dns_servers:
    type: comma_delimited_list
    description: DNS servers for the private network

# Moodle/Totara configuration

  site_name:
    type: string
    description: The value of the $SITENAME variable
    default: mdl1

  environment:
    type: string
    description: The value of the $ENVIRONMENT variable
    default:

  app_type:
    type: string
    description: The value of the $APPTYPE variable

  site_url:
    type: string
    description: The site URL

  git_repo:
    type: string
    description: Your git repo
    default: git://git.moodle.org/moodle.git

  git_branch:
    type: string
    description: Your git branch
    default: MOODLE_29_STABLE

# Database

  db_root_password:
    type: string
    description: Root password for PostgreSQL
    hidden: true
    constraints:
      - length: { min: 1, max: 41 }
        description: db_root_password must be between 1 and 41 characters
      - allowed_pattern: '[a-zA-Z0-9]*'
        description: db_root_password must contain only alphanumeric characters


resources:

# Networks and routers

  private_net:
    type: OS::Neutron::Net
    properties:
      name: {"Fn::Join": ['-',[{get_param: site_name}, 'net']]}

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net }
      cidr: { get_param: private_net_cidr }
      gateway_ip: { get_param: private_net_gateway }
      allocation_pools:
        - start: { get_param: private_net_pool_start }
          end: { get_param: private_net_pool_end }
      dns_nameservers: { get_param: private_net_dns_servers }

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_net }
      name: {"Fn::Join": ['-',[{get_param: site_name}, 'router']]}

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: private_subnet }

# Infrastructure layer

# Db and Web Server
  server:
    type: OS::Nova::Server
    properties:
      name: {"Fn::Join": ['-',[{get_param: site_name}, 'server']]}
      image: { get_param: image }
      flavor: { get_param: servers_flavor }
      key_name: { get_param: key_name }
      block_device_mapping:
        - device_name: vda
          volume_id: { get_resource: server_rootvol }
          delete_on_termination: false
      networks:
        - port: { get_resource: server_port }
      user_data:
        str_replace:
          template: { get_file: server.sh }
          params:
            site_name: { get_param: site_name }
            environment: { get_param: environment }
            app_type: { get_param: app_type }
            site_url: { get_param: site_url }
            db_rootpassword: { get_param: db_root_password }
            git_repo: { get_param: git_repo }
            git_branch: { get_param: git_branch }

  server_rootvol:
    type: OS::Cinder::Volume
    properties:
      name: {"Fn::Join": ['-',[{get_param: site_name}, 'rootvol']]}
      image: { get_param: image }
      size: 15

  server_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_net }
      fixed_ips:
        - subnet_id: { get_resource: private_subnet }
      security_groups: 
        - { get_param: secgroup_server }

  server_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
#      Floating network not supported in IceHouse
#      floating_network: { get_param: public_net }
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: server_port }
    depends_on: router_interface

outputs:

  server_private_ip:
    description: IP address of server in private network
    value: { get_attr: [ server, first_address ] }

  server_public_ip:
    description: Floating IP address of server1 in public network
    value: { get_attr: [ server_floating_ip, floating_ip_address ] }
    
  host_name:
    description: host name
    value: { get_param: [ site_url ] }



